import { GrammarDrill } from './grammarLibrary';

export const GRAMMAR_DRILLS: GrammarDrill[] = [
  // ─── 1. Tenses & Aspects ───────────────────────────────────────────────
  {
    id: 'tenses-present-perfect',
    moduleId: 'tenses',
    title: 'Present Perfect vs. Simple Past',
    ruleFormula: 'Subject + have/has + V3  vs.  Subject + V2',
    ruleSummary: 'Use Present Perfect for past actions with present consequences or uncompleted time frames. Use Simple Past for finished past events at a specific time.',
    difficultyLevel: 1,
    targetCategory: 'Verb Tenses',
    explanation: 'Notice how "has increased" emphasizes current status, while "increased in 2010" specifies a closed past timeframe.',
    sentences: [
      'Global urbanization has accelerated rapidly over the last three decades.',
      'Governments have implemented several policies to curb carbon emissions.',
      'Research has shown a clear link between exercise and cognitive health.',
      'The company introduced a new sustainability framework in 2021.',
      'Scientists have identified critical vulnerabilities in the ecosystem.',
      'Many developed nations experienced unprecedented economic growth during the twentieth century.',
    ],
  },
  {
    id: 'tenses-past-perfect',
    moduleId: 'tenses',
    title: 'Past Perfect for Chronological Sequence',
    ruleFormula: 'Subject + had + V3 (happened before another past action)',
    ruleSummary: 'Use Past Perfect to establish which of two past actions occurred first.',
    difficultyLevel: 2,
    targetCategory: 'Verb Tenses',
    explanation: 'Establishes clear temporal precedence before a secondary past benchmark.',
    sentences: [
      'Before the new regulations were enacted, factories had discharged waste freely.',
      'Researchers had gathered extensive data prior to launching the trial.',
      'The city had expanded significantly before city planners revised zoning laws.',
      'By the time the report was published, opinions had already shifted.',
      'The committee had reached a consensus before the director called the vote.',
    ],
  },
  {
    id: 'tenses-future-perfect',
    moduleId: 'tenses',
    title: 'Future Perfect & Completion',
    ruleFormula: 'Subject + will have + V3 + by [time]',
    ruleSummary: 'Expresses an action that will be completed prior to a specific point in the future.',
    difficultyLevel: 2,
    targetCategory: 'Verb Tenses',
    explanation: 'Projects completion relative to a future deadline.',
    sentences: [
      'By 2050, the population in major urban centers will have doubled.',
      'Scientists will have developed viable alternatives before fossil reserves collapse.',
      'By the end of this decade, automated systems will have transformed agriculture.',
      'The institute will have finalized the clinical trials by next spring.',
    ],
  },

  // ─── 2. Conditionals & Hypotheses ─────────────────────────────────────────
  {
    id: 'cond-third-conditional',
    moduleId: 'conditionals',
    title: 'Third Conditional (Unreal Past)',
    ruleFormula: 'If + Subject + had + V3, Subject + would have + V3',
    ruleSummary: 'Speculates about imaginary past situations that did not happen and their hypothetical past results.',
    difficultyLevel: 3,
    targetCategory: 'Conditionals',
    explanation: 'Essential for IELTS Task 2 counterfactual evaluation and analytical reflection.',
    sentences: [
      'If governments had invested earlier in renewable energy, emissions would have dropped significantly.',
      'Had the company foreseen the financial downturn, it would have diversified its holdings.',
      'If medical teams had detected the outbreak sooner, containment would have been achieved rapidly.',
      'If city officials had modernized infrastructure, traffic congestion would have been mitigated.',
      'Had strict regulations been enforced, environmental contamination would have been prevented.',
    ],
  },
  {
    id: 'cond-second-conditional',
    moduleId: 'conditionals',
    title: 'Second Conditional (Hypothetical Present/Future)',
    ruleFormula: 'If + Subject + Past Simple, Subject + would + V1',
    ruleSummary: 'Expresses hypothetical, unlikely, or imaginary situations in the present or future.',
    difficultyLevel: 2,
    targetCategory: 'Conditionals',
    explanation: 'Used when proposing theoretical policy solutions or imaginary choices.',
    sentences: [
      'If universities offered free tuition, higher education would become accessible to everyone.',
      'If public transport were free, urban pollution levels would decrease substantially.',
      'If companies rewarded remote productivity, employee turnover would diminish.',
      'If individuals consumed less single-use plastic, ocean pollution would decline rapidly.',
    ],
  },
  {
    id: 'cond-mixed-conditional',
    moduleId: 'conditionals',
    title: 'Mixed Conditionals (Past Cause → Present Result)',
    ruleFormula: 'If + Subject + had + V3, Subject + would + V1 (now)',
    ruleSummary: 'Connects an unfulfilled past action to a present hypothetical outcome.',
    difficultyLevel: 3,
    targetCategory: 'Conditionals',
    explanation: 'Binds past decisions directly to present consequences.',
    sentences: [
      'If planners had prioritized green spaces decades ago, cities would be far more livable today.',
      'Had the country embraced digital infrastructure earlier, its economy would be stronger now.',
      'If educators had integrated technology sooner, remote learning would be seamless today.',
    ],
  },

  // ─── 3. Modal Auxiliary Verbs ──────────────────────────────────────────────
  {
    id: 'modals-deduction-past',
    moduleId: 'modals',
    title: 'Past Modals of Deduction & Regret',
    ruleFormula: 'must have / should have / could have + V3',
    ruleSummary: 'Deduce past events (must have) or evaluate past errors and missed opportunities (should have / could have).',
    difficultyLevel: 3,
    targetCategory: 'Modal Verbs',
    explanation: 'Ideal for critical evaluation in academic essays.',
    sentences: [
      'Policymakers should have addressed regional infrastructure disparities much sooner.',
      'The unexpected anomaly must have resulted from calibration errors during setup.',
      'Analysts claim the central bank could have lowered interest rates to stimulate growth.',
      'The rapid collapse of the habitat must have been triggered by rising sea temperatures.',
    ],
  },
  {
    id: 'modals-hedging-academic',
    moduleId: 'modals',
    title: 'Academic Hedging with Modals',
    ruleFormula: 'may / might / could + V1',
    ruleSummary: 'Avoid overly definitive claims in academic writing by softening assertions with modal verbs.',
    difficultyLevel: 2,
    targetCategory: 'Modal Verbs',
    explanation: 'Academic tone requires cautious claims rather than absolute generalizations.',
    sentences: [
      'Excessive screen usage may contribute to reduced attention spans among young learners.',
      'Implementing strict tariffs might exacerbate existing trade tensions between nations.',
      'Higher taxation on sugary beverages could encourage healthier dietary choices.',
      'Automated diagnostic tools may assist physicians in identifying rare conditions early.',
    ],
  },

  // ─── 4. Connecting Words & Cohesion ────────────────────────────────────────
  {
    id: 'connectors-subordinating',
    moduleId: 'connectors',
    title: 'Subordinating Conjunctions & Contrast',
    ruleFormula: 'Although / Even though / Whereas + Clause, Main Clause',
    ruleSummary: 'Introduce concession or contrast within a single complex sentence structure.',
    difficultyLevel: 2,
    targetCategory: 'Cohesion & Coherence',
    explanation: 'Boosts Coherence & Coherence scores in IELTS Task 2 essays.',
    sentences: [
      'Although renewable technology has advanced, fossil fuels still dominate energy production.',
      'Whereas traditional retail relies on physical stores, e-commerce operates seamlessly online.',
      'Even though funding was limited, researchers completed the groundbreaking trial on schedule.',
      'While automation boosts industrial efficiency, it frequently displaces entry-level workers.',
      'Despite the high initial cost, electric vehicles offer substantial long-term savings.',
    ],
  },
  {
    id: 'connectors-causal-transitions',
    moduleId: 'connectors',
    title: 'Causal Discourse Markers',
    ruleFormula: 'Consequently, / Therefore, / As a result, + Sentence',
    ruleSummary: 'Connect sentences by showing clear cause-and-effect relationships.',
    difficultyLevel: 2,
    targetCategory: 'Cohesion & Coherence',
    explanation: 'Establishes logical flow across paragraph ideas.',
    sentences: [
      'Urban housing prices have skyrocketed; consequently, young professionals are moving outward.',
      'The region experienced severe drought; as a result, agricultural output declined by thirty percent.',
      'Digital literacy is now essential; therefore, schools must update their curricula accordingly.',
      'Strict conservation laws were introduced; subsequently, endangered species populations recovered.',
    ],
  },

  // ─── 5. Sentence Structure ────────────────────────────────────────────────
  {
    id: 'struct-relative-clauses',
    moduleId: 'structure',
    title: 'Non-Defining Relative Clauses',
    ruleFormula: 'Main Subject, who/which + Clause, Main Verb',
    ruleSummary: 'Embed additional descriptive information smoothly inside commas without breaking main sentence flow.',
    difficultyLevel: 2,
    targetCategory: 'Complex Grammar',
    explanation: 'Demonstrates grammatical range and sophisticated sentence architecture.',
    sentences: [
      'Artificial intelligence, which is transforming modern healthcare, requires ethical oversight.',
      'Dr. Aris, who led the global climate summit, emphasized immediate international cooperation.',
      'The solar farm, which covers five hundred hectares, supplies power to fifty thousand homes.',
      'Urban green spaces, which lower ambient city temperatures, improve resident mental well-being.',
    ],
  },
  {
    id: 'struct-passive-voice',
    moduleId: 'structure',
    title: 'Academic Passive Voice',
    ruleFormula: 'Subject + be + V3 + (by Agent)',
    ruleSummary: 'Shift focus to the action or object rather than the actor, standard in scientific and academic writing.',
    difficultyLevel: 2,
    targetCategory: 'Complex Grammar',
    explanation: 'Removes subjective personal pronouns and elevates academic register.',
    sentences: [
      'Significant advancements have been made in quantum computing architectures.',
      'Strict confidentiality protocols were maintained throughout the clinical trial.',
      'The proposal was rejected by the board due to insufficient environmental guarantees.',
      'Data from thousands of participants were analyzed using machine learning algorithms.',
    ],
  },
  {
    id: 'struct-cleft-sentences',
    moduleId: 'structure',
    title: 'Cleft Sentences for Emphasis',
    ruleFormula: 'It is/was [emphasized element] that/who + rest of sentence',
    ruleSummary: 'Structure sentences to place powerful focus on a specific cause, actor, or factor.',
    difficultyLevel: 3,
    targetCategory: 'Complex Grammar',
    explanation: 'High-level Band 9 stylistic structure.',
    sentences: [
      'It is through education that societies achieve long-term economic stability.',
      'What worries economists most is the persistent imbalance in global trade distribution.',
      'It was the sudden change in government policy that triggered widespread market volatility.',
    ],
  },

  // ─── 6. Parts of Speech & Grammar Mechanics ───────────────────────────────
  {
    id: 'parts-dependent-prepositions',
    moduleId: 'parts-of-speech',
    title: 'Dependent Prepositions & Collocations',
    ruleFormula: 'Verb/Adjective + specific preposition (e.g. attribute to, crucial for)',
    ruleSummary: 'Drill fixed prepositional pairings essential for precise, natural English phrasing.',
    difficultyLevel: 2,
    targetCategory: 'Grammar Mechanics',
    explanation: 'Eliminates common L2 preposition errors.',
    sentences: [
      'Economists attribute the recent inflation spike to supply chain disruptions.',
      'Clean water access is fundamental to preventing widespread disease outbreaks.',
      'The proposal is fully compatible with international environmental standards.',
      'Scholars frequently take exception to unverified empirical claims.',
      'Effective communication is paramount in resolving diplomatic disputes.',
    ],
  },
  {
    id: 'parts-adjective-order',
    moduleId: 'parts-of-speech',
    title: 'Adjective Stacking & Order',
    ruleFormula: 'Opinion → Size → Age → Shape → Color → Origin → Material → Purpose',
    ruleSummary: 'Practice standard natural adjective ordering before nouns.',
    difficultyLevel: 1,
    targetCategory: 'Grammar Mechanics',
    explanation: 'Trains intuitive placement of multiple descriptors.',
    sentences: [
      'The museum unveiled a magnificent ancient Greek marble statue.',
      'The institute occupies an impressive modern glass research facility.',
      'Engineers introduced an innovative compact electric propulsion system.',
    ],
  },
];
